// SPDX-License-Identifier: GPL-3.0
/*
    This file is part of the iden3 contracts developed by Iden3.

    This is a Groth16 proof verifier smart contract generated by SnarkJS.
    
    Note: This is a template that will be generated from your specific circuit.
    The actual verifier will be generated by running:
    > snarkjs zkey export solidityverifier circuit_final.zkey Groth16Verifier.sol
*/

pragma solidity >=0.7.0 <0.9.0;

contract Groth16Verifier {
    // Scalar field size
    uint256 constant r = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Base field size
    uint256 constant q = 21888242871839275222246405745257275088696311157297823756163051367270236165979;

    // Verification Key data
    struct VerifyingKey {
        Pairing.G1Point alpha;
        Pairing.G2Point beta;
        Pairing.G2Point gamma;
        Pairing.G2Point delta;
        Pairing.G1Point[] gammaAbc;
    }

    struct Proof {
        Pairing.G1Point a;
        Pairing.G2Point b;
        Pairing.G1Point c;
    }

    // Pairing library
    library Pairing {
        struct G1Point {
            uint X;
            uint Y;
        }

        struct G2Point {
            uint[2] X;
            uint[2] Y;
        }

        function P1() pure internal returns (G1Point memory) {
            return G1Point(1, 2);
        }

        function P2() pure internal returns (G2Point memory) {
            return G2Point([1, 0], [0, 1]);
        }

        function addition(G1Point memory p1, G1Point memory p2) internal view returns (G1Point memory r) {
            uint[4] memory input;
            input[0] = p1.X;
            input[1] = p1.Y;
            input[2] = p2.X;
            input[3] = p2.Y;
            bool success;

            assembly {
                success := staticcall(sub(gas(), 2000), 6, input, 0xc0, r, 0x60)
                switch success
                case 0 {
                    revert(0, 0)
                }
            }

            require(success, "pairing-add-failed");
        }

        function scalar_mul(G1Point memory p, uint s) internal view returns (G1Point memory r) {
            uint[3] memory input;
            input[0] = p.X;
            input[1] = p.Y;
            input[2] = s % r;

            bool success;
            assembly {
                success := staticcall(sub(gas(), 2000), 7, input, 0x80, r, 0x60)
                switch success
                case 0 {
                    revert(0, 0)
                }
            }

            require(success, "pairing-mul-failed");
        }

        function pairing(G1Point[] memory p1, G2Point[] memory p2) internal view returns (bool) {
            require(p1.length == p2.length, "pairing-lengths-failed");

            uint elements = p1.length;
            uint inputSize = elements * 6;
            uint[] memory input = new uint[](inputSize);

            for (uint i = 0; i < elements; i++) {
                input[i * 6 + 0] = p1[i].X;
                input[i * 6 + 1] = p1[i].Y;
                input[i * 6 + 2] = p2[i].X[0];
                input[i * 6 + 3] = p2[i].X[1];
                input[i * 6 + 4] = p2[i].Y[0];
                input[i * 6 + 5] = p2[i].Y[1];
            }

            uint[1] memory out;
            bool success;

            assembly {
                success := staticcall(sub(gas(), 2000), 8, add(input, 0x20), mul(inputSize, 0x20), out, 0x20)
                switch success
                case 0 {
                    revert(0, 0)
                }
            }

            require(success, "pairing-opcode-failed");
            return out[0] != 0;
        }
    }

    VerifyingKey verifyingKey;

    function setVerifyingKey() private {
        // This function should be populated with the actual verification key data
        // Generated by: snarkjs zkey export json circuit_final.zkey
        verifyingKey.alpha = Pairing.G1Point(
            20576839154369318784968206084906275831852103823253609152074196838255127866265,
            10103356849861024968330156533065397525820843814820788152768976932631222211756
        );

        // Beta, gamma, delta and gamma ABC points should be set here
        // This is a template - actual values from your circuit
    }

    function verify(uint[2] memory a, uint[2][2] memory b, uint[2] memory c, uint[3] memory input)
        public
        view
        returns (bool r)
    {
        Proof memory proof;
        proof.a = Pairing.G1Point(a[0], a[1]);
        proof.b = Pairing.G2Point([b[0][0], b[0][1]], [b[1][0], b[1][1]]);
        proof.c = Pairing.G1Point(c[0], c[1]);

        // Verify the proof
        return verifyProof(proof, input);
    }

    function verifyProof(Proof memory proof, uint[3] memory input)
        internal
        view
        returns (bool)
    {
        // Implementation of Groth16 verification
        // This verifies: e(proof.a, proof.b) = e(alpha, beta) * e(sum(input[i]*gamma_abc[i]), gamma) * e(proof.c, delta)

        require(input.length + 1 == verifyingKey.gammaAbc.length, "verifyProof-error");

        // Compute the linear combination vk_x
        Pairing.G1Point memory vk_x = verifyingKey.gammaAbc[0];
        for (uint i = 0; i < input.length; i++) {
            vk_x = Pairing.addition(
                vk_x,
                Pairing.scalar_mul(verifyingKey.gammaAbc[i + 1], input[i])
            );
        }

        // Check the pairing equation
        Pairing.G1Point[] memory p1 = new Pairing.G1Point[](4);
        Pairing.G2Point[] memory p2 = new Pairing.G2Point[](4);

        p1[0] = proof.a;
        p2[0] = proof.b;

        p1[1] = verifyingKey.alpha;
        p2[1] = verifyingKey.beta;

        p1[2] = vk_x;
        p2[2] = verifyingKey.gamma;

        p1[3] = proof.c;
        p2[3] = verifyingKey.delta;

        return Pairing.pairing(p1, p2);
    }
}
